### ISSUE TITLE
Ciprofloxacin opthalmic ointment (RxNorm) mapped to 'Direct acting vasodilator' in ETC

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#87] opened 2016-07-24 17:37 UTC
I presume this is a bug in the mapping, though perhaps there's something unusual clinically that I'm not aware of.  The consequence for this inadvertent mapping is:  if you define 'hypertensive agents' using the high-level class in ETC, you get 'ciprofloxacin' as one of the ingredients.

**Comment by dimshitc** [comment] 2016-08-03 14:24
Yeah, it's a bug. We'll work on it.

**Comment by ericaVoss** [comment] 2016-08-31 01:16
Looks like this is gone in 20160817?

```{sql}
SELECT *
FROM CONCEPT c
	JOIN CONCEPT_RELATIONSHIP cr
		ON cr.concept_id_1 = c.CONCEPT_ID
	JOIN concept c2
		ON c2.concept_id = cr.concept_id_2
WHERE c.CONCEPT_NAME LIKE '%hypertensive agents%'
AND c.VOCABULARY_ID = 'ETC'
AND c2.concept_class_id = 'Ingredient'
ORDER BY 1
```

**Comment by ericaVoss** [comment] 2016-12-21 22:25
@pbr6cornell  and @cgreich - this is no longer an issue correct?

**Comment by cgreich** [comment] 2016-12-22 01:41
Can't reproduce it. Concepts with lower(concept_name) like '%hypertensive agents%' are all Plumonary Antihypertensive Agents, and none of them has a relationship to Cipro. If you use the concept_ancestor table, as you should, you get:

select a.min_levels_of_separation as a_min,
  an.concept_id as an_id, an.concept_name as an_name, an.vocabulary_id as an_vocab, an.domain_id as an_domain, an.concept_class_id as an_class,
  de.concept_id as de_id, de.concept_name as de_name, de.vocabulary_id as de_vocab, de.domain_id as de_domain, de.concept_class_id as de_class
from concept an
join concept_ancestor a on a.ancestor_concept_id=an.concept_id
join concept de on de.concept_id=a.descendant_concept_id
where lower(an.concept_name) like '%hypertensive agents%'
and an.vocabulary_id='ETC'
and de.concept_class_id='Ingredient'
order by an.concept_id, min_levels_of_separation;

They are all good.

**Comment by ericaVoss** [comment] 2016-12-22 13:49
@cgreich  then let's close this issue.  I cannot because I didn't open it.

**Comment by ericaVoss** [comment] 2017-10-15 23:48
@pbr6cornell or @cgreich could you please close the issue?  I cannot.

**Closed** 2017-10-16 00:27 UTC
Labels: bug

**Comment by cgreich** [comment] 2017-10-16 02:09
Patrick beat me to it.
