### ISSUE TITLE
Issue in CDM v5 (Gender) Vocabulary

### ISSUE THREAD

**Issue by Vipugupt** [OHDSI/Vocabulary-v5.0#778] opened 2023-02-24 17:25 UTC
The SQL server model shared in below link has a constraint to link primary key and Foreign key between concept and concept_synonym is violating. 
Script link: https://github.com/OHDSI/CommonDataModel/blob/main/inst/ddl/5.4/sql_server/OMOPCDM_sql_server_5.4_constraints.sql

Constraint: 
ALTER TABLE @cdmDatabaseSchema.CONCEPT_SYNONYM ADD CONSTRAINT fpk_CONCEPT_SYNONYM_language_concept_id FOREIGN KEY (language_concept_id) REFERENCES @cdmDatabaseSchema.CONCEPT (CONCEPT_ID);

The Language concept ids present in CONCEPT_SYNONYM doesn't available in CONCEPT table.
Please help us in getting it resolved.

**Comment by TinyRickC137** [comment] 2023-02-25 09:15
Hello, @Vipugupt 
Gender or language?

The problem seems to be on your side. Some concept_ids are missing from the concept table. Can you, maybe, re-download and rebuild your tables?

**Comment by Vipugupt** [comment] 2023-02-27 05:12
Hi @TinyRickC137,

I have just started looking into OMOP model and Athena vocabulary.
I am pretty new to it.

Is there any linking between the multiple vocabularies. Like- if we want to use 1 vocabulary then there are prerequisite to have other vocabularies as well. If yes? then do we have it defined anywhere?

Thanks in advance for the guidance.

**Comment by TinyRickC137** [comment] 2023-02-27 08:42
It is, actually. 

The whole idea is using multiple vocabularies with connections between them. You can go to [Athena](https://athena.ohdsi.org/search-terms/start), and click the download button. Certain vocabularies would be pre-checked. This is sort of a standard package. Depending on your needs, you can check other vocabularies as well. 

More information on the vocabularies is here ([Book of OHDSI](https://ohdsi.github.io/TheBookOfOhdsi/StandardizedVocabularies.html)) and also you are welcome to ask questions on the [OHDSI forum](https://forums.ohdsi.org/). There is also a [youtube channel](https://www.youtube.com/@OHDSI) with tutorials. 

I will close this issue because the problem is on your side, so feel free to ask questions on the forum. 
Best regards/

**Closed by TinyRickC137** 2023-02-27 08:42 UTC
