### ISSUE TITLE
Redundant concepts?

### ISSUE THREAD

**Issue by murphyke** [OHDSI/Vocabulary-v5.0#52] opened 2015-07-01 22:05 UTC
Concepts 44818792 and 44818890 seem to have the same meaning, at least as far as the concept table goes.

```
select * from concept where concept_id in (44818792, 44818890);
-[ RECORD 1 ]----+-------------------------
concept_id       | 44818792
concept_name     | Associated with (SNOMED)
domain_id        | Metadata
vocabulary_id    | Relationship
concept_class_id | Relationship
standard_concept |
concept_code     | OMOP generated
valid_start_date | 1970-01-01
valid_end_date   | 2099-12-31
invalid_reason   |
-[ RECORD 2 ]----+-------------------------
concept_id       | 44818890
concept_name     | Associated with (SNOMED)
domain_id        | Metadata
vocabulary_id    | Relationship
concept_class_id | Relationship
standard_concept |
concept_code     | OMOP generated
valid_start_date | 1970-01-01
valid_end_date   | 2099-12-31
invalid_reason   |
```

**Comment by cgreich** [comment] 2015-07-02 17:12
Yes, they are the symmetrical opposites of each other. The name doesn't do justice. You can see it here:
select * from relationship where relationship_concept_id in (44818792, 44818890);
I'll rename.

**Comment by murphyke** [comment] 2015-07-02 18:02
Thanks.  So they are "**X** *associated with, flavor 1* **(finding) Y**" and "**(Finding) Y** *associated with, flavor 2* **X**".  Presumably if you were asserting an "associated with" relationship between two findings, you could use either one ....

**Comment by cgreich** [comment] 2015-07-03 02:44
No, you can't. Because all relationships have a direction. I will rename them to "Has association finding" and "Finding associated with" or something. The problem is that SNOMED actually defines these names, and we are not supposed to change them. Let me take a look what they have, and maybe there are synonyms.

**Comment by ericaVoss** [comment] 2016-03-15 02:27
This is an old/small issue but still exists in **v5.0 11-MAR-16**.

**Comment by cgreich** [comment] 2016-03-15 06:49
Fixed now

**Closed** 2016-04-16 14:15 UTC
