### ISSUE TITLE
ICD-10-CM double mappings to SNOMED 

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#203] opened 2019-02-03 19:36 UTC
In my version of vocabulary (v5.0 18-JAN-19), I am observing ~18,000 ICD-10-CM codes that have >=2 mappings to SNOMED-CT in the condition domain (so, would represent scenarios where source records would split into multiple standard records).

In reviewing these ICD-10-CM, many seem like appropriate mappings.  I notice that if often seems that one of the two SNOMED codes that is mapped appears to be quite broad.  I presume this is to preserve all post-coordinated elements of the original source code, but wonder if there's some logic guiding this or whether some are errors. 

Some specific examples:

M08.01 is ICD-10-CM code for 'Unspecified juvenile rheumatoid arthritis, shoulder'.    This maps to SNOMED IDS:  4253901, 40483262 , which are  'Juvenile rheumatoid arthritis' and 'Arthritis of shoulder region joint'.     My question #1 here:  'Arthritis of shoulder' seems too broad of a mapping.

M08.011 is ICD-10-CM code for 'Unspecified juvenile rheumatoid arthritis, right shoulder', which maps to SNOMED IDs:  4253901, 4114439, which are 'Juvenile rheumatoid arthritis' and 'Rheumatoid arthritis of shoulder'.    Question #2:  'Rheumatoid arthritis of shoulder' may be too broad.   Question #3:  why did M08.01 and M08.011 end up with different mappings? (one going to arthritis and other going to rheumatoid arthritis)

**Comment by cgreich** [comment] 2019-02-03 19:41
@pbr6cornell: You pinpoint a well-understood problem. The only clean solution is are SNOMED extension concepts. We are talking to SNOMED about them actually picking them up. But it's early days.

The solution now is the best you can have. If you want to search for patients with juvenile rheumatoid arthritis of the shoulder you will not find a standard concept (SNOMED doesn't have it, it's too granular). So, you need to search for rheumatoid arthritis, and arthritis of the shoulder at the same day. That way, you will find those patients correctly. 

The problem is ATLAS doesn't know how to do such gymnastics out of the box. We wanted to start the conversation with the ATLAS team, but only after we know what SNOMED is going to do.

**Comment by p-talapova** [comment] 2019-02-05 11:45
@pbr6cornell: Thank you for reporting! 

As mentioned by @cgreich, there are a lot of concepts in all versions of ICD, that don't have direct mappings in the SNOMED. That's why we had to map them to more than one standard concept to cover all important features ( e.g. condition, localization, laterality, gender etc.). In a case of indirect mapping, we use the closest to each other concepts  according to the SNOMED hierarchy, that help us to save as more attributes as possible, as in this instance:

M08.01	Unspecified juvenile rheumatoid arthritis, shoulder
Maps to 40483262	443798008	Arthritis of shoulder region joint - is about related pathological process and localization 
Maps to 4253901	410795001	Juvenile rheumatoid arthritis - is about the particular disorder

But mappings of similar concept 'M08.011	Unspecified juvenile rheumatoid arthritis, right shoulder' (4253901	410795001	Juvenile rheumatoid arthritis and 4114439	201766009	Rheumatoid arthritis of shoulder) are incorrect. 
Because Juvenile rheumatoid arthritis is not Rheumatoid arthritis. They are separate nosological entities. 
So, we will fix this soon!

**Comment by vojtechhuser** [comment] 2019-03-07 16:14
To answer you question 1 - the only solution is to open the pandora box of not-exact mapping.

Have a concept of mapping that is narrow to broad.

Currently OMOP only knows exact mapping. This seems to ignore the reality.

**Comment by dimshitc** [comment] 2019-03-08 12:51
We are working on SNOMED Extension where we create a new concepts that will represent all ICDs that don't have equivalent mapping in SNOMED.

**Comment by dimshitc** [comment] 2019-04-08 19:35
@p-talapova did you fixed?

**Comment by p-talapova** [comment] 2019-04-09 09:22
Yes, I did. Currently, 'M08.011 Unspecified juvenile rheumatoid arthritis, right shoulder' maps to both  
'759884  1074611000119101  Arthritis of joint of right shoulder region' and  '4253901  410795001  Juvenile rheumatoid arthritis'. However, to build the SNOMED Extension, we should provide a full review of the 'M' ICD-10-CM chapter as soon as possible.

**Comment by dimshitc** [comment] 2019-04-09 09:33
I'm closing this one becasue this issue was about incorrect mapping. But SNOMED Extension creation is a totally different story.

**Closed by dimshitc** 2019-04-09 09:33 UTC
