### ISSUE TITLE
Standard concept for race of 'Black'

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#19] opened 2015-01-30 18:58 UTC
There are two standard concepts for 'Black',  one is 'Black' the other is 'Black or African American'.  I recommend we choose one to be standard and set the other as non-standard, mapping to the first as standard.  Since 'Black of African American' appears to be the broader of the two concepts, I recommend it to be the standard, but I'm open to choosing the other.  Otherwise, if we don't pick one,, it's not clear which to choose in ETL.

**Comment by cgreich** [comment] 2015-01-30 19:55
Well, The problem is that one is the higher level in the hierarchy, and the other one is the lower. Just like "Asian" and "Chinese". Of course, the races are massively wishy washy. What we could do is only allow the highest 5 races, and the other ones get mapped into this. So, all "Chinese" in the source data woudl turn into "Asian". Should we?

**Comment by pbr6cornell** [comment] 2015-01-30 21:31
I agree with that proposal:   "Chinese" could be stored in the SOURCE_CONCEPT_ID field if that was truly the source value, but it seems it'd be better to unify on a more restricted, consistent set of concepts to impose as standard.

**Comment by cgreich** [comment] 2015-01-31 14:49
Patrick:

 

You got it.

 

Speaking off: Look at the last statement here: http://forums.ohdsi.org/t/laertes-pre-load-queries-hoi-from-x-to-snomed-rxnorm-bd-to-cd/180/7. Need your input here. We have Clinical/Branded Drugs, and then the equivalent of them as packs and quantified drugs. Should we only make one of them standard, and officially map the others to it?

**Comment by ericaVoss** [comment] 2018-06-22 15:11
```sql
SELECT *
FROM CONCEPT
WHERE VOCABULARY_ID = 'RACE'
AND INVALID_REASON IS NULL
```

Could we close this issue?  Or are we taking action here.  

I'm actually wondering if it is even appropriate to streamline these.

**Comment by cgreich** [comment] 2018-06-22 19:04
Close the issue. I am tired of fixing races. They are nonsense. I am sure somebody sees a great difference in "Black", "African" and "African American".

**Comment by ericaVoss** [comment] 2018-06-22 19:13
Agree, @pbr6cornell  close the issue please.

**Closed** 2018-08-02 12:39 UTC
Labels: enhancement
