### ISSUE TITLE
Is epiglottis part of oropharynx?

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#1003] opened 2024-05-06 20:23 UTC
SELECT a.ancestor_concept_id,
        a.descendant_concept_id,
        c.concept_name
FROM cdm.concept_ancestor a
inner join cdm.concept c
on descendant_concept_id = concept_id
WHERE ancestor_concept_id = 4181338
and concept_name like '%epiglottis%'
and vocabulary_id = 'SNOMED'

here 4181338 is Malignant tumor of oropharynx

![image](https://github.com/OHDSI/Vocabulary-v5.0/assets/13936600/2845a498-5b6c-4ed5-9600-0da0f5e52710)

**Comment by aostropolets** [comment] 2024-05-06 20:49
the general comment to this issue and issue before: yes, snomed thinks so

**Comment by gowthamrao** [comment] 2024-05-06 21:10
similar https://github.com/OHDSI/Vocabulary-v5.0/issues/1002

sounds good @aostropolets  . luckily we can exclude them in our cohort definitions!

**Comment by m-khitrun** [comment] 2024-05-07 07:43
Hello, @gowthamrao
This looks very much weird. We should report these issues to SNOMED.

**Comment by gowthamrao** [comment] 2024-05-07 12:46
very weird. anatomically incorrect. 

My follow-up question: how does a user know if it is SNOMED issue (i.e. SNOMED did it, so OMOP has it) vs. OMOP made a mistake. 

eg. this i am assuming is a OMOP mistake? https://github.com/OHDSI/Vocabulary-v5.0/issues/994

**Comment by vladkorsik** [comment] 2024-05-10 12:27
It seems that the history with anterior epiglottis cancer extends beyond anatomical classification. Upon closer examination, the anatomical axis of the larynx remains intact and accurate  in SNOMED.  https://athena.ohdsi.org/search-terms/terms/4189377

Therefore, the underlying cause likely resides within the cancerous component. This is a particularly intriguing aspect, considering the functional significance of the epiglottis in humans, serving as a protective barrier against aspiration. We may assume that it comes into contact with the same environments  as oral cavity/oropharynx do, so It's more than larynx ad more than oropharynx. This, in turn, may entail a greater array of factors influencing carcinogenesis.

Even the AJCC (American Joint Committee on Cancer) demonstrates some complexity in how and where to code/stage cancers originated in epiglottis. Notably, epiglottis mentioned in  T categories  in  both oropharynx and larynx chapters.

@m-khitrun I believe the idea to address this issue to SNOMED is great, it necessitates a more focused approach. Perhaps framing the question around the underlying reasons for such intricacies, questioning whether it is an error, and if not, understanding the rationale behind it, would be beneficial.

**Comment by m-khitrun** [comment] 2024-05-17 07:10
So, I've asked SNOMED editors about this hierarchy of malignant neoplasm and the answer was the following:

"We have reviewed the models of these concepts. These issues were caused by incorrect hierarchical relationships in the anatomy and they have been fixed by the following changes:

The incorrect superconcept oropharynx has been removed from the concepts: "anterior epiglottis" and "surface of anterior epiglottis". The related neoplasmic disorders have been remodelled.
The root of the tongue should not be part of the supraglottis and it has been fixed.

These changes will be included in the July 2024 release."

Please, note, that, our August release will not capture these changes as we use the February 2024 version of SNOMED CT International for this refresh.

**Closed** 2024-05-17 14:06 UTC
Labels: SNOMED
