### ISSUE TITLE
Missing CPT4 Modifier '21'

### ISSUE THREAD

**Issue by Piper-Ranallo** [OHDSI/Vocabulary-v5.0#648] opened 2022-07-01 20:11 UTC
CPT4 modifier '21' (inactivated in 2009) seems to be missing from the concept table. Should this be added?

Original defintion:

WARNING: Code Deleted 2009-01-01
21 - Prolonged Evaluation and Management Services: When the face-to-face or floor/unit service(s) provided is prolonged or otherwise greater than that usually required for the highest level of evaluation and management service within a given category, it may be identified by adding modifier 21 to the evaluation and management code number. A report may also be appropriate.Toggle Dictionary Definitions

**Comment by cgreich** [comment] 2022-07-02 20:23
We could, @Piper-Ranallo, but is there the slightest shadow of a use case here?

**Comment by Piper-Ranallo** [comment] 2022-07-05 13:02
I guess my assumption is that each vocabulary contains all historical concepts (active and inactive) so we can capture the meaning of data at the time it was encoded.  The use case for having the complete set of modifiers is two-fold. One, it allows us to capture this aspect of services provided. Two, it allows us to identify when we have non-industry standard modifiers applied to procedures encoded using HCPCS or CPT codes. This modifier appeared in the set of "invalid modifiers" (based on a join to modifier concepts in the concept file) but in fact it's not (it's just missing in omop).

Does that make sense?

**Comment by cgreich** [comment] 2022-09-05 16:30
We could use a cutoff date or squeaky wheel-based criterion. 

Which is why I was asking @Piper-Ranallo: Do you want to analyze data with those modifiers for anything in particular? Right now, the modifier essentially says "took longer than normal". I get it. But apart of having a home for this data item, do we actually need it?

**Comment by Piper-Ranallo** [comment] 2022-09-06 17:56
Hi @cgreich and @mik-ohdsi,

This request is came out of a data quality assurance use case (v a specific research use case). We were  trying to identify source data with potentially invalid modifiers. 

I may have made the erroneous assumption that omop vocabulary tables contain all historically valid codes for each of the vocabularies.  However, I do think there's value in OMOP including these, as any industry standard code seems to be created for a reason - and therefore has potential value to researchers.

I've since loaded the complete set of modifiers into our teminology server and am using that (rather than omop vocabulary) fiels as the 'source of truth' for what represents a valid v. invalid HCPCS or CPT modifier. 

Piper

**Comment by cgreich** [comment] 2022-09-08 19:05
> I may have made the erroneous assumption that omop vocabulary tables contain all historically valid codes for each of the vocabularies.

You made the right assumption. OMOP never forgets. But we may not have all historical codes. We need the community (you) tell us.

The problem is not in the code. We are abolishing the other modifiers as well. They are not a thing. Some of them modify the procedure, some of them a condition, some of them are justifications for payment, some of them are care settings of the visit. We will map them where they belong.

A "took longer than usual" modifier - I don't know where that fits, to be honest. Do you?

**Comment by mik-ohdsi** [comment] 2022-11-02 11:50
Hi @Piper-Ranallo and @cgreich  - from the discussion I take that a) this is a claims related modifier probably  justifying a higher price tag b) we have not a clear use case nor do we know if anyone really has this in their source data AND wants it to appear in the OMOP CDM - are you okay with closing this ticket?

**Comment by Piper-Ranallo** [comment] 2022-11-02 16:17
@mik-ohdsi , yes, let's close it. The juice isn't worth the squeeze (as they say) on this one.
We have it in our source data, but have a lot more work to do figuring out which modifiers carry any useful clinical information and therefore are worth keeping and mapping.

Thanks,
Piper

**Closed** 2023-06-01 10:17 UTC
Labels: CPT4
