### ISSUE TITLE
PPI concepts moved to Measurement domain from Observation?  v5.0 17-MAR-19

### ISSUE THREAD

**Issue by ksdkalluri** [OHDSI/Vocabulary-v5.0#216] opened 2019-04-08 23:56 UTC
All of Us Research Program has been using `v5.0 22-DEC-17` and we are planning to upgrade to `v5.0 17-MAR-19`. In Concept table there are a lot of concepts for which the domain has been changed since the old version for the PPI Vocabulary.
for eg.

```sql
select *
from v1.concept 
where concept_id in (1585596, 1585597, 1585598, 1585260, 1585252, 1585246, 1585247, 1585248, 1585249, 1585250, 1585259)
```
gives result

![Screen Shot 2019-04-08 at 2 40 55 PM](https://user-images.githubusercontent.com/23404801/55764018-b5203a00-5a37-11e9-84fb-f15257539b02.png)

```sql
select *
from v2.concept 
where concept_id in (1585596, 1585597, 1585598, 1585260, 1585252, 1585246, 1585247, 1585248, 1585249, 1585250, 1585259)
```
gives result

![Screen Shot 2019-04-08 at 2 43 04 PM](https://user-images.githubusercontent.com/23404801/55764000-a2a60080-5a37-11e9-9acf-58d5b4b7a6e2.png)

To make sure I checked http://athena.ohdsi.org for one of the concept_id from the above query `1585260` which is concept_id for e-mail. I found out that the `Non-standard to Standard map(OMOP)` is linked to `LOINC` instead of `PPI`.

![Screen Shot 2019-04-08 at 2 53 19 PM](https://user-images.githubusercontent.com/23404801/55764027-bf423880-5a37-11e9-85a0-117fb6b05fbe.png)

For all the concepts with `Non-standard to Standard map(OMOP)` linked to `LOINC` Vocabulary instead of `PPI`, the domain is being changed from `observation` to `measurement`.

But most of the concepts like e-mail, First_name, phone etc. belong to `Observation` domain rather that the `measurement`.

is this change intentional?

I also found that 139 `PPI` to `PPI` `concept_ancestor` records missing in the new version, Not sure if it both issues are related.

**Comment by dimshitc** [comment] 2019-04-09 10:06
duplicate of https://github.com/OHDSI/OMOP-Standardized-Vocabularies/issues/35

**Closed by dimshitc** 2019-04-09 10:06 UTC
